# Copyright 2026 Кислов Роман Сергеевич
# Licensed under the Apache License, Version 2.0.
apiVersion: v2
name: godhcp
description: GoDHCP DHCPv4 server
type: application
version: 0.1.0
appVersion: "0.1.0"
